# Generated by Django 5.0.6 on 2026-05-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "card_count",
                    models.PositiveIntegerField(default=0, verbose_name="card count"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_decks",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "flashcard deck",
                "verbose_name_plural": "flashcard decks",
                "db_table": "flashcard_decks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField(verbose_name="front")),
                ("back", models.TextField(verbose_name="back")),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="review count"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="correct count"
                    ),
                ),
                (
                    "last_reviewed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last reviewed"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="flashcards.flashcarddeck",
                    ),
                ),
            ],
            options={
                "verbose_name": "flashcard",
                "verbose_name_plural": "flashcards",
                "db_table": "flashcards",
                "ordering": ["order"],
            },
        ),
    ]
