# Generated by Django 5.0.6 on 2026-05-03 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=10, verbose_name="question count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="question")),
                ("options", models.JSONField(default=list, verbose_name="options")),
                (
                    "correct_answer",
                    models.CharField(max_length=10, verbose_name="correct answer"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="explanation"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(default=dict, verbose_name="user answers"),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="score")),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total questions"
                    ),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="correct count"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz attempt",
                "verbose_name_plural": "quiz attempts",
                "db_table": "quiz_attempts",
                "ordering": ["-started_at"],
            },
        ),
    ]
