# Generated by Django 5.0.6 on 2026-04-30 21:10

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Text File"),
                        ],
                        max_length=10,
                        verbose_name="file type",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File bayt", verbose_name="file size"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from file",
                        verbose_name="extract text",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(default=0, verbose_name="page count"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="word count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "documents",
                "verbose_name_plural": "documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="documents_user_id_31091e_idx",
                    ),
                    models.Index(fields=["status"], name="documents_status_f31a08_idx"),
                ],
            },
        ),
    ]
